apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csdp
patches:
- path: ingress-patch.json
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1
resources:
- ../../base
# - ingress.yaml
# - rbac.yaml         # created earlier as part of this process
# - artifact-repo.yaml # created earlier as part of this process
patchesStrategicMerge:
- |
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: workflow-controller-configmap
  data:
    artifactRepository:  |
      archiveLogs: true
      s3:
        bucket: csdp-lr
        endpoint: s3.amazonaws.com
        region: us-east-1
