apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csdp
patches:
- path: ingress-patch.json
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1
- target:
    group: apps
    version: v1
    name: argo-server
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/1
      value: --auth-mode-client
resources:
  - ../../base
  - ingress.yaml
  - rbac.yaml         # created earlier as part of this process
  - artifact-repo.yaml # created earlier as part of this process
patchesStrategicMerge:
  - |
 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: argo-server
   annotations:
     <endpoint>/role-arn: s3.amazonaws.com/role-arn = arn:aws:iam::835357571861:role/argo-workflows-s3-artifact-repo
 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: workflow-controller-configmap
 data:
   workflowDefaults: |
     spec:
       serviceAccountName: workflow
